name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_matrix:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Cache rust
        uses: actions/cache@v3
        env:
          cache-name: cache-rust
        with:
          path: target
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Cache go
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-go-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install nats-server
        run: go get github.com/nats-io/nats-server/v2

      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: |
          rustup update
          cargo test --features=unstable -- --nocapture

